import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#FFFFFF",
  },
  titleWraper: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    width: "100%",
    height: 88,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 11,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    borderBottomWidth: 1,
    marginBottom: 32,
  },
  title: {
    marginLeft: "auto",
    marginRight: "auto",
    fontFamily: "Roboto-Medium",
    fontSize: 17,
    lineHeight: 22,
    color: "#212121",
  },
  form: {
    paddingLeft: 16,
    paddingRight: 16,
    marginBottom: 32,
  },
  postPhotoWraper: {
    position: "relative",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 8,
    width: "100%",
    height: 240,
    backgroundColor: "#F6F6F6",
    borderRadius: 8,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    borderWidth: 1,
  },
  addPhotoButton: {
    position: "absolute",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 60,
    backgroundColor: "#ffffff",
    borderRadius: 50,
  },
  addButtonText: {
    marginBottom: 32,
    fontSize: 16,
    color: "#BDBDBD",
  },
  formInputWraper: {
    marginBottom: 32,
  },
  formInput: {
    width: "100%",
    height: 50,
    marginBottom: 16,
    fontSize: 16,
    color: "#212121",
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    borderBottomWidth: 1,
  },
  mapWraper: {
    position: "relative",
  },
  mapButton: {
    position: "absolute",
    top: 13,
  },
  formSubmitButton: {
    width: "100%",
    height: 51,
    marginBottom: 111,
    padding: 16,
    borderRadius: 100,
    backgroundColor: "#F6F6F6",
  },
  formSubmitButtonText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#BDBDBD",
  },
  controlsWraper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 39,
    width: "100%",
    height: 90,
  },
  trashButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: "auto",
    marginRight: "auto",
    width: 70,
    height: 40,
    backgroundColor: "#F6F6F6",
    borderRadius: 20,
  },
});
