import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
  },
  imageWraper: {
    marginLeft: "auto",
    marginRight: "auto",
    top: -60,
    width: 120,
    height: 120,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
  },
  addButton: {
    position: "absolute",
    bottom: 14,
    right: -14,
    backgroundColor: "#FFFFFF",
    borderColor: "#FFFFFF",
    borderRadius: 50,
    borderWidth: 0,
  },
  form: {
    width: "100%",
    height: "70%",
    marginTop: "auto",
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingLeft: 16,
    paddingRight: 16,
  },
  formHeader: {
    margin: 0,
    padding: 0,
    marginTop: -32,
    marginBottom: 32,
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
  },
  formInputWraper: {
    display: "flex",
    gap: 16,
    marginBottom: 43,
  },
  unfocusedInput: {
    height: 50,
    padding: 16,
    backgroundColor: "#F6F6F6",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    borderRadius: 8,
  },
  focusedInput: {
    height: 50,
    padding: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#FF6C00",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    borderRadius: 8,
  },
  passwordWraper: {
    position: "relative",
  },
  passwordShowBtn: {
    position: "absolute",
    right: 16,
    top: 16,
  },
  passwordShowBtnText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#1B4371",
  },
  formSubmitButton: {
    width: "100%",
    height: 51,
    marginBottom: 16,
    padding: 16,
    borderRadius: 100,
    backgroundColor: "#FF6C00",
  },
  formSubmitButtonText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#ffffff",
  },
  regButtonText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    textAlign: "center",
    color: "#1B4371",
  },
});
