import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    backgroundColor: "#FFFFFF",
  },
  titleWraper: {
    position: "relative",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "flex-end",
    width: "100%",
    height: 88,
    paddingLeft: 10,
    paddingRight: 10,
    paddingBottom: 11,
    borderStyle: "solid",
    borderColor: "#E8E8E8",
    borderBottomWidth: 1,
  },
  title: {
    marginLeft: "auto",
    marginRight: "auto",
    fontFamily: "Roboto-Medium",
    fontSize: 17,
    lineHeight: 22,
    color: "#212121",
  },
  userInfoWraper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    height: 60,
    paddingLeft: 16,
    paddingRight: 16,
    marginTop: 32,
  },
  userInfoPhoto: {
    width: 60,
    height: 60,
    borderRadius: 16,
  },
  userInfoName: {
    fontFamily: "Roboto-Bold",
    fontSize: 13,
    lineHeight: 15,
  },
  userInfoEmail: {
    fontFamily: "Roboto-Regular",
    fontSize: 11,
    lineHeight: 13,
  },
  addButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    height: 40,
    backgroundColor: "#FF6C00",
    borderRadius: 20,
  },
  controlsWraper: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 39,
    width: "100%",
    height: 90,
    marginTop: "auto",
    borderStyle: "solid",
    borderTopWidth: 1,
    borderColor: "#E8E8E8",
    
},
});
